# Generated by Django 4.1.3 on 2022-11-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.IntegerField(primary_key=True, serialize=False)),
                ("nome_usuario", models.CharField(max_length=45)),
                ("imagem_codificada", models.CharField(max_length=5000)),
                ("nivel_acesso", models.IntegerField()),
            ],
        ),
    ]
